### ISSUE TITLE
A define whose parent is a user-defined type warns "Cannot find type named"

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#425]
## Description

A `define` whose parent is a type the author defined earlier in the same file is reported as an unknown type:

```
Cannot find type named `companion`
```

The warning is wrong: `companion` is defined a few lines above, the compile produces no error, and the resulting program is correct — the instance is registered under the user type exactly as it should be. Only the diagnostic is wrong, so the editor shows a warning on valid code.

The same shape with a builtin parent (`define O as character with … end`) produces no warning, so it is specifically a user-defined parent that is not recognised.

## Reproduction

1. Compile the script below.
2. Read the diagnostics.

```sparkdown
define companion as character with
  store trust = 0
end

define O as companion with
  name = "Orion"
end

scene only
  Hello.
end
```

Diagnostics: `severity=2 (Warning), line 4: Cannot find type named \`companion\``.

Taken with a scratch test (not committed) in `packages/sparkdown/src/tests/compiler/`, compiling the source above through `SparkdownCompiler` under the player worker's configuration (`useBuiltinsPrelude: true`, `seedBuiltinsIntoStory: true`) and flattening `program.diagnostics`, which is keyed by uri rather than an array:

```sh
cd packages/sparkdown && NODE_OPTIONS="--max-old-space-size=2048" npx vitest run src/tests/compiler/<file>.test.ts --pool=forks --poolOptions.forks.minForks=1 --poolOptions.forks.maxForks=1
```

The matrix, with a control that must warn:

| Script | Diagnostics | Correct? |
| --- | --- | --- |
| `define companion as character` then `define O as companion` | `Cannot find type named \`companion\`` (line 4) | no |
| `define O as companion` then `define companion as character` (reversed) | `Cannot find type named \`companion\`` (line 0) | no |
| `define O as character` (builtin parent) | none | yes |
| `define companion as character` alone | none | yes |
| `define O as nosuchtype` (control) | `Cannot find type named \`nosuchtype\`` | yes |

Order does not matter, so it is not a declaration-ordering problem.

## Expected behavior

A `define` whose parent is a type declared anywhere in the program compiles without a diagnostic, the same as one whose parent is a builtin type.

## Actual behavior

A warning is reported against the parent type name. The compiled program is otherwise correct — see Analysis — so the effect is a spurious warning in the editor's problems list on valid, working code.

This is the pattern the repo's own compile fixtures use: `__snapshots__/compile/define/with-numeric-property.sd` declares `define companion as character with …` and `__snapshots__/compile/define/with-string-properties.sd` declares `define O as companion with …`. Those fixtures compile in isolation, one file each, so neither ever has the parent present and the warning never shows up there.

## Environment

- Surface: web editor and VS Code extension (diagnostics); the compiled program is unaffected
- Version or commit: `863c5a0b9` (branch `perf/416-outside-flow-invalidation`; the code involved is unmodified from `origin/main` at `4183ce3c4`)
- OS and browser, or VS Code version: not applicable — reproduces headlessly in vitest

## Analysis

**Confirmed: the data the validator needs is present, and it still reports the type as missing.** Dumping `program.context` for the reproduction script gives:

- `program.context.companion` exists, and its keys are `["O"]` — the user type is a real type namespace and the instance is registered under it.
- `program.context.character` has keys `["$default", "companion"]` — `companion` is also registered as an instance of `character`, as expected.

So lowering and registration are both correct, and the defect is in the reference-validation pass rather than in the data.

**Suspected line.** The diagnostic is produced at `packages/sparkdown/src/compiler/classes/SparkdownCompiler.ts:4818-4830`, the `Report missing error` branch. The `type named \`X\`` wording comes from the `selector && selector.types ? \`type named \\\`${selector.types[0]}\\\`\`` arm:

```ts
const message = `Cannot find ${validDescription}`;
const severity = invalidStylingStringIdentifier
  ? DiagnosticSeverity.Error
  : DiagnosticSeverity.Warning;
```

It is reached when `resolveSelectorMemo` (`:4630`, wrapping `resolveSelector(program, selector, expectedSelectorTypes)` at `:4647`) returns nothing for every selector on the reference. Given that `program.context.companion` exists, the likely cause is that the set the resolver validates a parent type against is built from the builtin definitions (`this._config.definitions?.builtins`, used for the sibling check at `:4705`) rather than from the program's own types. I did not confirm that by changing it, so treat the exact line as a hypothesis; the confirmed part is that the context contains the type and the diagnostic fires anyway.

**What must stay true after a fix.** The control row must keep warning: `define O as nosuchtype` is a genuine mistake and has to stay a warning. A fix that simply stops validating parent types would silence both.

## Additional context

Found while investigating an unrelated compiler claim during PR #420 for #416, by sweeping `define` shapes to check whether any of them affected incremental reuse. They do not — that part of the sweep came back clean — but this diagnostic showed up in the output.

Related: #416 and PR #420 touch the same file but not this pass. The struct registry and define-as-class work in the history around `define` is the area a fixer will want to read first.

Workaround: none for the warning itself. It is cosmetic — the compiled program is correct — so it can be ignored, at the cost of a permanent false entry in the problems list for any project that defines its own types.
